# Playbook to create alone GCE instance with SSH-RSA Key
---
- name: Playbook test to create gce instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    service_account_email: example@example.lab.gserviceaccount.com  # Replace with you CGE Account Service
    credentials_file: example.json # Replace with you GCE User JSON Key File
    project_id: example # Replace with you GCE Project ID
    machine_type: n1-standard-1
    image: centos-7
  tasks:
    - name: vmgce01
      gce:
        zone: us-east1-b
        instance_names: vmgce01
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        metadata: '{"sshKeys":"gmail_user:ssh-rsa"}' # Replace gmail_user with you GCE Account User. ssh-rsa with you ssh-rsa computer.
