- name: Playbook test to create gce instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    service_account_email: labansible@laboratorioansible.iam.gserviceaccount.com
    credentials_file: laboratorioansible-GCE.json
    project_id: laboratorioansible
    machine_type: n1-standard-1
    image: centos-7
  tasks:
    - name: Create GCE load balancer
      gce_lb:
        name: lbserver
        state: present
        region: us-east1
        members: ['us-east1-b/web01','us-east1-b/web02','us-east1-b/web03']
        httphealthcheck_name: hc
        httphealthcheck_port: 80
        httphealthcheck_path: "/"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
