# Playbook to create GCE instance with Apache
---
- name: Playbook to create gce instance with apache
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    service_account_email: example@example.lab.gserviceaccount.com  # Replace with you CGE Account Service
    credentials_file: example.json # Replace with you GCE User JSON Key File
    project_id: example # Replace with you GCE Project ID
    instance_names: web01,web02,web03
    machine_type: n1-standard-1
    image: centos-7
  tasks:
    - name: Create firewall rule to allow http traffic
      gce_net:
        name: default
        fwname: "my-http-fw-rule"
        allowed: tcp:80
        state: present
        src_range: "0.0.0.0/0"
        target_tags: "http-server"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
    - name: Create an Instance based on image {{ image }}
      gce:
        zone: us-east1-b
        instance_names: "{{ instance_names }}"
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        state: present
        preemptible: true
        tags: http-server,https-server
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        metadata: '{"sshKeys":"gmail_user:ssh-rsa"}' # Replace gmail_user with you GCE Account User. ssh-rsa with you ssh-rsa computer.
      register: gce
    - name: Save host data within a Group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: gce_instances_temp
      with_items: "{{ gce.instance_data }}"
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
      with_items: "{{ gce.instance_data }}"
    - name: setting fact
      set_fact: host={{ item.public_ip }}
      with_items: "{{ gce.instance_data }}"
- name: Configure instance post-creation
  hosts: gce_instances_temp
  gather_facts: true
  remote_user: gmail_user # Replace with you GCE Account User
  become: yes
  become_method: sudo
  roles:
    - ansibleweb
