# Playbook to set authorized keys
---
- name: Set authorized key
  hosts: all
  tasks:
    - name: Keys
      authorized_key:
        user=root
        state=present
        key="{{ lookup('file', 'my_key.pub') }}" # Replace my_key.pub with you file key name
