# Playbook to add in /etc/hosts an entry
---
- name: Set hostname
  hosts: servers
  tasks:
    - name: Add Satellite host
      lineinfile:
        path: /etc/hosts
        line: 'xxx.xxx.xxx.xxx  srv.example.lab srv' # Replace with your info
        state: present
