---
# tasks file for ansibleweb
- name: install apache package
  yum:
    name: httpd
    state: latest
- name: Install Firewalld package
  yum:
    name: firewalld
    state: latest
- name: Template Out Apache Configuration File
  template:
    backup: yes
    src: apache_httpdconf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0444
  notify:
    - restart apache
  when: apache_enable
- name: Template Out Apache Configuration File
  template:
    src: apache_indexhtml.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0444
  when: apache_enable
- name: start and enable apache daemon
  service:
    name: httpd
    state: started
    enabled: true
  when: apache_enable
- name: start and enable firewalld daemon
  service:
    name: firewalld
    state: started
    enabled: true
  when: apache_enable
- name: open http firewalld port
  firewalld:
    port: 80/tcp
    immediate: true
    permanent: true
    state: enabled
  when: apache_enable
